[package]
name = "abc215"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "0.8.2"

[profile.release]
lto = true
panic = 'abort'
